### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by meandus** [epicmaxco/vuestic-admin#745]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  **- [x] bug report**
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
**bug**

* **What is the current behavior?**
**Impossible to build Dockerfile**

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
```
Docker version 19.03.8, build afacb8b
MacOS Catalina 10.15.3 (19D76)
Visual Studio Code
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

1. install Vuestic installer
```
npm install -g vuestic-installer
```

2. Vuestic a new project
```
XXX % vuestic vuestic
 __     __          ____  _   _      
 \ \   / /   _  ___/ ___|| |_(_) ___ 
  \ \ / / | | |/ _ \___ \| __| |/ __|
   \ V /| |_| |  __/___) | |_| | (__ 
    \_/  \__,_|\___|____/ \__|_|\___|
                                     
vuestic has been successfully created.
```

2. Modify .dockerignore to add .git into docker (Because of git rev-parse HEAD)

```
node_modules/
dist/
# .git/
.dockerignore
.gitattributes
.gitignore
Dockerfile
README.md
```

3. build Dockerfile

```
docker build --rm -f "Dockerfile" -t vuestic:latest "vuestic"
```

* **What is the expected behavior?**
**A Docker image**

* **What is the motivation / use case for changing the behavior?**
**Would like to run project into the Dockerfile provided**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Seems to be here:
```
const getLastCommitHash = () => {
  const hash = require('child_process').execSync('git rev-parse HEAD')
    .toString()

  return hash.slice(0, 6)
}
```

and here
```
new webpack.DefinePlugin({
        VERSION: JSON.stringify(version),
        TIMESTAMP: JSON.stringify(timeStamp),
        COMMIT: JSON.stringify(getLastCommitHash()),
      }),
```

```
XXX % docker build --rm -f "Dockerfile" -t vuestic:latest "vuestic"
Sending build context to Docker daemon  5.779MB
Step 1/7 : FROM node:8
 ---> 8eeadf3757f4
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> ae53738b9d7a
Step 3/7 : COPY . /app
 ---> 1602768e7d08
Step 4/7 : EXPOSE 8082
 ---> Running in 7c02792ba6d0
Removing intermediate container 7c02792ba6d0
 ---> 88e58b684741
Step 5/7 : RUN npm install http-server -g
 ---> Running in 0e80aabe2224
/usr/local/bin/http-server -> /usr/local/lib/node_modules/http-server/bin/http-server
/usr/local/bin/hs -> /usr/local/lib/node_modules/http-server/bin/http-server
+ http-server@0.12.1
added 26 packages from 35 contributors in 7.255s
Removing intermediate container 0e80aabe2224
 ---> 74d8c3fcf86d
Step 6/7 : RUN npm install && npm run build
 ---> Running in a07a73acdbc2

> yorkie@2.0.0 install /app/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done


> node-sass@4.13.0 install /app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-57_binding.node
Download complete
Binary saved to /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.13.0/linux-x64-57_binding.node

> core-js@2.6.11 postinstall /app/node_modules/babel-polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.10 postinstall /app/node_modules/babel-runtime/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.4.5 postinstall /app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /app/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@2.6.11 postinstall /app/node_modules/vuestic-ui/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> flag-icon-css@3.4.5 postinstall /app/node_modules/flag-icon-css
> opencollective-postinstall || true

Thank you for using flag-icon-css!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/lipis/donate


> node-sass@4.13.0 postinstall /app/node_modules/node-sass
> node scripts/build.js

Binary found at /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1872 packages from 1185 contributors and audited 935248 packages in 183.315s

24 packages are looking for funding
  run `npm fund` for details

found 40071 vulnerabilities (40063 low, 8 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> vuestic-admin@2.0.0 build /app
> vue-cli-service build

 ERROR  TypeError: Function.prototype.toString requires that 'this' be a Function
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Proxy.toString (<anonymous>)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:47:27)
    at foldKey (/app/node_modules/hash-sum/hash-sum.js:28:12)
    at Array.reduce (<anonymous>)
    at foldObject (/app/node_modules/hash-sum/hash-sum.js:26:32)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:45:12)
    at foldKey (/app/node_modules/hash-sum/hash-sum.js:28:12)
    at Array.reduce (<anonymous>)
    at foldObject (/app/node_modules/hash-sum/hash-sum.js:26:32)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:45:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuestic-admin@2.0.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuestic-admin@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by asvae** [comment]
Thanks for informing.
