### ISSUE TITLE
While building docker image it fails

### ISSUE THREAD

**Issue by championshuttler** [epicmaxco/vuestic-admin#753]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

Build docker image fails 

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

Run `docker build -t vuestic .`

Get this error

```
> vuestic-admin@2.0.0 build /app
> vue-cli-service build

 ERROR  TypeError: Function.prototype.toString requires that 'this' be a Function
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Proxy.toString (<anonymous>)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:47:27)
    at foldKey (/app/node_modules/hash-sum/hash-sum.js:28:12)
    at Array.reduce (<anonymous>)
    at foldObject (/app/node_modules/hash-sum/hash-sum.js:26:32)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:45:12)
    at foldKey (/app/node_modules/hash-sum/hash-sum.js:28:12)
    at Array.reduce (<anonymous>)
    at foldObject (/app/node_modules/hash-sum/hash-sum.js:26:32)
    at foldValue (/app/node_modules/hash-sum/hash-sum.js:45:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuestic-admin@2.0.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuestic-admin@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T00_29_53_103Z-debug.log
The command '/bin/sh -c npm install && npm run build' returned a non-zero code: 1

```

* **What is the expected behavior?**

Image should be build

**Comment by asvae** [comment]
Pleas create different issue if something similar happens in new version (we'll have release in a couple of days.
